# Copyright 2020 The Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |
      Deployment template for the Platform Serices
      RocketChat helper app reggie.
    iconClass: icon-node
  name: ${APPLICATION_NAME}
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: reggie-config
      labels:
        app: ${APPLICATION_NAME}
    data:
      SSO_HOST_URL: ${SSO_HOST_URL}
      SSO_REALM: ${SSO_REALM}
      #SSO_USERNAME
      #SSO_PASSWORD
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_SENDER: ${EMAIL_SENDER}
      #EMAIL_CONFIRMATION_JWT_SECRET
      #EMAIL_INVITATION_JWT_SECRET
      #SSO_CLIENT_SECRET
      API_URL: ${HOST}
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${APPLICATION_NAME}
      annotations:
        description: Route for reggies API services
      labels:
        app: ${APPLICATION_NAME}
    spec:
      host: "${HOSTNAME_HTTPS}"
      path: /reggie/api
      port:
        targetPort: 8000-tcp
      to:
        kind: Service 
        name: ${APPLICATION_NAME}
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
        certificate: |-
          ${TLS_CERT_PEM}
        key: |-
          ${TLS_KEY_PEM}
        caCertificate: |-
          ${TLS_CACERT_PEM}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      selector:
        deploymentconfig: ${APPLICATION_NAME}
      ports:
        - name: 8000-tcp
          port: 8000
          protocol: TCP
          targetPort: 8000
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${APPLICATION_NAME}
            from:
              kind: ImageStreamTag
              name: "${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}"
              namespace: ${SOURCE_IMAGE_NAMESPACE}
      replicas: 1
      selector:
        app: ${APPLICATION_NAME}
        role: api
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
            role: api
          name: ${APPLICATION_NAME}
        spec:
          containers:
            - name: ${APPLICATION_NAME}
              image: " "
              startupProbe:
                httpGet:
                  path: /api/v1/ehlo
                  port: 8000
                failureThreshold: 11
                periodSeconds: 3
              readinessProbe:
                httpGet:
                  path: /api/v1/ehlo
                  port: 8000
                timeoutSeconds: 3
              ports:
                - containerPort: 8000
              envFrom: 
                - secretRef:
                    name: reggie-creds
                - configMapRef:
                    name: reggie-config
              resources:
                limits:
                  cpu: 50m
                  memory: 256Mi
                requests:
                  cpu: 20m
                  memory: 128Mi
          #     volumeMounts:
          #       - name: config-vol
          #         mountPath: /opt/app-root/src/build/config/config.json
          #         subPath: config.json
          # volumes:
          #   - name: config-vol
          #     configMap:
          #       name: ${APPLICATION_NAME}-config
parameters:
  - description:
      The name assigned to all of the objects defined in this template.  You
      should keep this as default unless your know what your doing.
    displayName: APPLICATION_NAME
    name: APPLICATION_NAME
    required: true
    value: reggie-api
  - description:
      The namespace of the OpenShift project containing the
      imagestream for the application.
    displayName: Environment namespace
    name: NAMESPACE
    required: true
  - description: The openshift project where builds and target images are stored.
    displayName: Build Project
    name: SOURCE_IMAGE_NAMESPACE
    required: true
  - description: The name of the source image.
    displayName: Source Image Name
    name: SOURCE_IMAGE_NAME
    value: reggie-api
    required: true
  - description: The tag of the source image.
    displayName: Source Image Tag
    name: SOURCE_IMAGE_TAG
    required: true
  - name: SSO_REALM
    description:
    requred: true
  - name: EMAIL_HOST
    description:
    requred: true
  - name: EMAIL_PORT
    description:
    requred: true
  - name: EMAIL_SENDER
    description:
    requred: true
  - name: SSO_HOST_URL
    description:
    requred: true
  - name: TLS_CERT_PEM
    description: TLS certificate data in PEM format.
    displayName: TLS Certificate
    required: true
  - name: TLS_KEY_PEM
    description: |
      TLS certificate private key data in PEM format. This will be in
      the possesion of the person who created the Certificate Signing
      Request (CSR).
    displayName: TLS Private Key
    required: true
  - name: TLS_CACERT_PEM
    description: |
      TLS certificate cuthority certificate data in PEM format. If you 
      got your certificate from an iStore request, use L1KChain.txt.
    displayName: TLS Certificate Authority Certificate
    required: true
  - name: HOSTNAME_HTTPS
    description: Hostname serving the application
    displayName: Route Name
    required: true