kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit
  namespace: placeholder
subjects:
  - kind: ServiceAccount
    name: default
    namespace: 87d478-tools
  - kind: ServiceAccount
    name: pipeline
    namespace: placeholder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
