kind: Job
apiVersion: batch/v1
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
  name: set-vault-path
spec:
  template:
    metadata:
      name: set-vault-path
    spec:
      containers:
        - name: set-vault-path
          image: 'docker.io/bcgovdevops/utility-server:latest'
          env:
            - name: MYNAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MYCLUSTER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['clustername']
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              echo -n "CLUSTERNAME=" > /tmp/clustername &&
              oc get pods -o custom-columns=NODE:.spec.nodeName --no-headers=true | head -1 | cut -d "-" -f 2 >> /tmp/clustername &&
              . /tmp/clustername &&
              oc patch statefulset mongodb -p "{\"spec\": {\"template\": {\"metadata\": {\"annotations\": {\"vault.hashicorp.com/auth-path\": \"auth/k8s-$CLUSTERNAME\"}}}}}" &&
              oc patch deployment reggie-api -p "{\"spec\": {\"template\": {\"metadata\": {\"annotations\": {\"vault.hashicorp.com/auth-path\": \"auth/k8s-$CLUSTERNAME\"}}}}}" &&
              oc patch deployment rocketchat -p "{\"spec\": {\"template\": {\"metadata\": {\"annotations\": {\"vault.hashicorp.com/auth-path\": \"auth/k8s-$CLUSTERNAME\"}}}}}" &&
              oc patch deployment mongodb-backup -p "{\"spec\": {\"template\": {\"metadata\": {\"annotations\": {\"vault.hashicorp.com/auth-path\": \"auth/k8s-$CLUSTERNAME\"}}}}}"
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: dockerhub-bcgovdevops
      restartPolicy: OnFailure
