---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: s2i-nodejs-pipeline
spec:
  params:
    - name: IMAGE
      description: Location of the repo where image has to be pushed
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/bcgov/rocketchat
        # - name: subdirectory
        #   value: reggie/web
        - name: deleteExisting
          value: "true"
    - name: build-artifacts
      taskRef:
        name: do-stuff
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-image
      taskRef:
        name: binary-build
      runAfter:
        - build-artifacts
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: BUILD_NAME
          value: reggie-web-image-build
