# Copyright 2021 The Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: do-stuff
spec:
  workspaces:
    - name: source
      mountPath: /workspace/source
  steps:
    - name: where-am-i
      image: quay.io/openshift/origin-cli:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash

        pwd
        ls -lah
    - name: npm-scripts
      image: registry.access.redhat.com/ubi8/nodejs-14:latest
      workingDir: $(workspaces.source.path)/reggie/web
      script: |
        #!/usr/bin/env bash

        npm ci
        npm run build --if-present
    # This is an in-line Dockerfile could be added to a build
    # similar to show `docerkfile:` would be used in a `BuildConfig`.
    - name: add-dockerfile
      image: quay.io/openshift/origin-cli:latest
      workingDir: $(workspaces.source.path)/reggie/web
      script: |
        #!/usr/bin/env bash

        pushd build

        # Some things we don't want included our image build.
        cat <<EOF >.dockerignore
          .dockerignore
          Dockerfile
        EOF

        # The Dockerfile. I told `oc start-build` what directory to
        # upload so its going to expect the `Dockerfile` to be there.
        cat <<EOF >Dockerfile
          FROM caddy:latest

          ENV SUMMARY="Reggie Web ${APP_VERSION}"  \
              DESCRIPTION="Reggie Web ${APP_VERSION} served from Caddy"
          ENV LC_ALL=en_US.UTF-8 \
              LANG=en_US.UTF-8

          LABEL summary="$SUMMARY" \
              description="$DESCRIPTION"

          RUN mkdir -p /srv

          WORKDIR /srv

          COPY . /srv

          RUN ls -lah /srv

          EXPOSE 2015
        EOF

        popd
