# Copyright 2020 The Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |
      Deployment template for the RocketChat reverse proxy.
  name: ${NAME}
objects:
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      host: ${REDIR_SOURCE_HOST}
      port:
        targetPort: 2015-tcp
      tls:
        termination: edge
      to:
        kind: Service
        name: ${NAME}
        weight: 100
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${NAME}-config
      labels:
        app: ${NAME}
    data:
      Caddyfile: |
        ${SOURCE_URL}:2015  {
          reverse_proxy * ${DESTINATION_URL}  {
            header_up Host {http.reverse_proxy.upstream.hostport}
            header_up Sec-WebSocket-Protocol {>Sec-WebSocket-Protocol}
            header_up X-Real-IP {remote_host}
            header_up X-Forwarded-For {remote_host}
            header_up X-Forwarded-Proto {scheme}
            #header_up Connection {>Connection}
            #header_up Upgrade {>Upgrade}
            flush_interval -1
          }
          
          respond /ehlo 200

          log {
            # errors stdout
            output stdout 
            #format single_field common_log
            level DEBUG
          }
        }

        :2015 {
          respond /ehlo 200
            
          log {
            # errors stdout
            output stdout 
            #format single_field common_log
            level DEBUG
          }
        }
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      selector:
        role: proxy
      ports:
        - name: 2015-tcp
          port: 2015
          protocol: TCP
          targetPort: 2015
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ConfigChange
      replicas: 1
      selector:
        role: proxy
      template:
        metadata:
          labels:
            app: ${NAME}
            role: proxy
          name: ${NAME}
        spec:
          containers:
            - name: ${NAME}
              imagePullPolicy: Always
              image: "caddy:latest"
              env:
                - name: XDG_DATA_HOME
                  value: /tmp
              startupProbe:
                httpGet:
                  path: /
                  port: 2015
                  scheme: HTTP
                failureThreshold: 5
                periodSeconds: 3
              readinessProbe:
                httpGet:
                  path: /
                  port: 2015
                timeoutSeconds: 10
              ports:
                - containerPort: 2015
              resources:
                limits:
                  cpu: 60m
                  memory: 64Mi
                requests:
                  cpu: 30m
                  memory: 36Mi
              volumeMounts:
                - name: config-vol
                  mountPath: /etc/caddy/Caddyfile
                  subPath: Caddyfile
          volumes:
            - name: config-vol
              configMap:
                name: ${NAME}-config
          imagePullSecrets:
            - name: bcdevops-dockercfg
parameters:
  - description:
      The name assigned to all of the objects defined in this template.  You
      should keep this as default unless your know what your doing.
    displayName: Name
    name: NAME
    required: true
    value: rocketchat-proxy
  - name: DESTINATION_URL
    description:
      The destination address that is being proxied.
    displayName: Redirect Destination
    required: true
  - name: SOURCE_URL
    description: |
      The route that will be redirected to the destination URL.
    displayName: Front Door Route
    required: true