---
kind: Template
apiVersion: v1
metadata:
  name: ${APPLICATION_NAME}
  annotations:
    description: "Rocket.Chat Route Deployment"
    tags: "rocketchat"
objects:
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${APPLICATION_NAME}
      annotations:
        description: Route for application's http service.
      labels:
        app: ${APPLICATION_NAME}
    spec:
      host: "${HOSTNAME_HTTPS}"
      port:
        targetPort: 3000-tcp
      to:
        kind: Service 
        name: ${APPLICATION_NAME}
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
        certificate: |-
          ${TLS_CERT_PEM}
        key: |-
          ${TLS_KEY_PEM}
        caCertificate: |-
          ${TLS_CACERT_PEM}
parameters:
  - name: APPLICATION_NAME
    description: The name assigned to the application
    displayName: Application Name
    required: true
    value: rocketchat-server
  - name: TLS_CERT_PEM
      displayName: TLS Certificate
      description: TLS certificate data in PEM format.
      required: true
  - name: TLS_KEY_PEM
    displayName: TLS Private Key
    description: TLS certificate private key data in PEM format.
    required: true
  - name: TLS_CACERT_PEM
    displayName: TLS Certificate Authority Certificate
    description: |
      TLS certificate cuthority certificate data in PEM format.
    required: true
