---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |
      This configmap is used internally by the server to override
      settings.
  name: rocketchat-config
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: rocketchat-config
      app: ${APPLICATION_NAME}
    data: |-
      ${ROCKETCHAT_OVERWRITE_PROPERTIES}
parameters:
  - name: APPLICATION_NAME
    description: |
      The name assigned to the application
    displayName: Application Name
    required: true
    value: rocketchat-server
  - name: ROCKETCHAT_OVERWRITE_PROPERTIES
    description: |
      These properties will override any configuration stored internally
      in RocketChat's database.
    displayName: Server Override Properties
    required: true
