kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: reggie-web-artifact-build
  namespace: 87d478-tools
  labels:
    app: reggie-web
    name: reggie-web-artifact-build
spec:
  output:
    to:
      kind: DockerImage
      name: 'artifacts.developer.gov.bc.ca/r6e2-reggie/reggie-web-artifacts:latest'
    pushSecret:
      name: artifactory-push
  resources:
    limits:
      cpu: '2'
      memory: 4Gi
    requests:
      cpu: '1'
      memory: 2Gi
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 1
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:10'
      env:
        - name: BUILD_LOGLEVEL
          value: '5'
      incremental: false
  source:
    type: Git
    git:
      uri: 'https://github.com/bcgov/rocketchat.git'
      ref: master
    contextDir: reggie/web
  runPolicy: Serial
