apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: mobile-signing-service
metadata:
  name: mobile-signing-service
objects:
  - apiVersion: security.devops.gov.bc.ca/v1alpha1
    kind: NetworkSecurityPolicy
    metadata:
      name: any-to-any
    spec:
      description: |
        allow all pods to communicate
      source:
        - - "$namespace=${NAMESPACE}"
      destination:
        - - "$namespace=*"
  - apiVersion: security.devops.gov.bc.ca/v1alpha1
    kind: NetworkSecurityPolicy
    metadata:
      name: any-to-external
    spec:
      description: |
        Allow all pods to talk to external systems
      source:
        - - "$namespace=${NAMESPACE}"
      destination:
        - - "ext:network=any"
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: deny-by-default
    spec:
      podSelector: {}
      ingress: []
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      podSelector: {}
      policyTypes:
        - Ingress
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-server-to-mongo
    spec:
      # Allow the server to talk to the mongo
      # database cluster on the given port.
      podSelector:
        matchLabels:
          statefulset: mongodb
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  role: server
          ports:
            - protocol: TCP
              port: 27017
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-backup-to-mongo
    spec:
      # Allow the backup pod to talk to the mongo
      # database cluster on the given port.
      podSelector:
        matchLabels:
          statefulset: mongodb
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  role: backup
          ports:
            - protocol: TCP
              port: 27017
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-mongo-replication
    spec:
      # Allow the mongo pods to replicate
      podSelector:
        matchLabels:
          statefulset: mongodb
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  statefulset: mongodb
          ports:
            - protocol: TCP
              port: 27017
parameters:
  - name: NAMESPACE
    displayName: Namespace
    description: |
      The namespace this policy is being deployed to;
    required: true
